packer/pmm.json
test image - https://s3.amazonaws.com/percona-vm/PMM-Server-2018-08-31-1253.ova
=> PMM-2835 use SATA for OS drive

ansible/roles/pmm2-images/tasks/main.yml
https://pmm.cd.percona.com/job/pmm-submodules/job/PR-425
=> PMM-4518 Remove '/etc/nginx/conf.d/default.conf'

ansible/roles/pmm2-images/tasks/main.yml
https://pmm.cd.percona.com/job/pmm-submodules/job/PR-426/2
=> PMM-4518 Update nginx to the latest version

ansible/pmm/main.yml, ansible/roles/mysql-init/tasks/main.yml, packer/pmm.json
https://pmm.cd.percona.com/job/pmm-ami/612/
=> PMM-4518 Fix PMM 1.x AMI/OVF builds.

ansible/roles/pmm2-images/tasks/main.yml
https://pmm.cd.percona.com/job/pmm-submodules/job/PR-438/
=> PMM-4345 Remove rds_exporter rpm

ansible/roles/pmm2-images/tasks/main.yml
https://pmm.cd.percona.com/job/pmm-submodules/job/PR-446/8/
=> PMM-4353 remove systemd remnants

ansible/pmm2/post-build-actions.yml, ansible/roles/pmm2-images/tasks/main.yml, ansible/roles/pmm2-images/vars/main.yml
https://pmm.cd.percona.com/job/pmm-submodules/job/PR-448/
=> PMM-4658 use release repository for images builds

ansible/roles/postgres-init/tasks/main.yml, ansible/roles/postgres-init/vars/main.yml
https://github.com/Percona-Lab/pmm-submodules/pull/470
=> PMM-4708 Use 'release' repo for postgres rpms

ansible/pmm2/post-build-actions.yml
https://jira.percona.com/browse/PMM-4400
FB: https://github.com/Percona-Lab/pmm-submodules/pull/514
=> PMM-4400 Create file with virtualization type.

ansible/roles/ami-ovf/tasks/main.yml, ansible/roles/ami-ovf/vars/main.yml, packer/pmm2.json
https://github.com/Percona-Lab/pmm-submodules/pull/523
https://pmm.cd.percona.com/job/pmm2-ovf-slava/22/console
=> PMM-4928 Enable pmm2 testing repo for ami/ovf images for their build

ansible/pmm2/post-build-actions.yml, ansible/roles/pmm2-images/vars/main.yml
https://github.com/Percona-Lab/pmm-submodules/pull/586
=> PMM-5181 Use 'origin testing' repo for autobuilds.

ansible/roles/lvm-init/templates/resize-xfs-lvm
ami-09d7b617d0c79e7b0  for tests
=> PMM-5271 Fix automaticaly resizing of LVM volumes

ansible/roles/pmm2-images/tasks/main.yml
=> PMM-5655 remove leftovers of grafana plugins

ansible/roles/pmm2-images/tasks/main.yml
Reverts Percona-Lab/percona-images#72
=> Revert "PMM-5655 remove leftovers of grafana plugins"

ansible/roles/pmm2-images/tasks/main.yml
Added `percona-alertmanager` package for **Install RPMs** task
=> PMM-5558 install alertmanager

ansible/pmm/main.yml
Create **/.pmm-ami** and **/.pmm-ovf** files
=> PMM-5813 touch files

ansible/roles/pmm2-images/tasks/main.yml
Enabled local repo to be able to install new packages that are not present in main repo.
=> PMM-6119 enabled local repo

ansible/roles/pmm2-images/tasks/main.yml
Reverts Percona-Lab/percona-images#78
=> Revert "PMM-6119 enabled local repo"

ansible/roles/pmm2-images/tasks/main.yml
https://github.com/Percona-Lab/pmm-submodules/pull/1070
=> PMM-6119 Adding dbaas-controller

ansible/roles/pmm2-images/tasks/main.yml
=> PMM-6389 Add VictoriaMetrics

ansible/roles/pmm2-images/tasks/main.yml
Reverts Percona-Lab/percona-images#82
=> Revert "PMM-6389 Add VictoriaMetrics"

ansible/roles/cloud-node/tasks/main.yml
Reverts Percona-Lab/percona-images#91
=> Revert "PMM-6007 add machine ip address in ovf"

ansible/pmm2/post-build-actions.yml
https://github.com/Percona-Lab/pmm-submodules/pull/1394
=> PMM-7103 remove all pmm bootstrap logs

ansible/roles/pmm2-images/tasks/main.yml
FB https://github.com/Percona-Lab/pmm-submodules/pull/1429
=> PMM-6766 remove qan-app

ansible/roles/supervisord-init/tasks/main.yml, packer/pmm2.json
https://jira.percona.com/browse/PMM-3352
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1755
=> PMM-3352: Increase number of open files limit for jobs

ansible/roles/supervisord-init/tasks/main.yml
caused by PMM-3352, which is OK on VM or host, but requires additional changes for docker on host.
=> PMM-8180: Increase limits only for VMs

ansible/pmm2/post-build-actions.yml
=> PMM-8040 cleanup yum cache

ansible/pmm2/post-build-actions.yml, ansible/roles/pmm2-images/tasks/main.yml
https://github.com/Percona-Lab/pmm-submodules/pull/1856
=> PMM-8266 remove prometheus from image
